### ISSUE TITLE
revise explanatory note & sourceline

### ISSUE THREAD

**Issue by smyerslens** [TheLens/citysalaries#12]
Source line: New Orleans Civil Service Department

i would use the explantory note on the existing app and edit as necessary. there are some impt caveats on there (such as mayoral appointees) that we need to keep. except for the part about obtaining it under the La pub records act; that’s good.

**Comment by myersnews** [comment]
Also note that salaries are rounded to the nearest dollar.

**Comment by smyerslens** [comment]
add link to “pay plan” in note
remove question mark in note about full-time employees (I'm making that a separate issue)
revise this sentence:  In some cases, employees may have different job titles than those listed here, such as some mayoral appointees.
to:  Some employees, such as mayoral appointees, may have different job titles than those listed here.

**Comment by ThomasThoren** [comment]
Fixed in 107fc0dea3fc7e6bec55923c02bb46ae91a0e6bb.
