### ISSUE TITLE
Salaries with cents are getting cut off

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/citysalaries#21]
Ex. $40,000.80 is being shown as $40,000.8.

**Comment by smyerslens** [comment]
Round to nearest dollar in all cases.

**Comment by smyerslens** [comment]
Actually disregard that. Just fix that issue.

**Comment by ThomasThoren** [comment]
Fixed with 353868962b55abe3d4ffd6fe05e0b0a69ad97c11.
