### ISSUE TITLE
"council member" search doesn't come up w/any results

### ISSUE THREAD

**Issue by smyerslens** [TheLens/citysalaries#29]
It's a suggested search so if that's the incorrect term, let's suggest another one.

**Comment by ThomasThoren** [comment]
See #30. Once I'm done cleaning department data, the dropdowns will only show departments that have matches in the data.

**Comment by smyerslens** [comment]
10-4

## 

Steve Myers
Special projects editor
The Lens http://thelensnola.org/, New Orleans' first independent,
nonprofit news site
504-298-9750
@myersnews http://twitter.com/myersnews

**Comment by ThomasThoren** [comment]
Should be fixed for all departments and positions. Fixed in 466df7aeb521409cdf74bfcf3c6213b056a71b9f.
