### ISSUE TITLE
delay in autosuggest on names

### ISSUE THREAD

**Issue by smyerslens** [TheLens/citysalaries#33]
We may want to take off autosuggest on this field because it's so resource-intensive.

**Comment by ThomasThoren** [comment]
Do you see a lag when using a laptop? It seems fine for me on mine, but I see a considerable lag on my phone. We might only need to remove it from mobile devices.

**Comment by smyerslens** [comment]
I don't see a lag on my latoptop now, but I believe my comment from before was. However I do see a lag on the phone. For the purposes of simplicity, I think we remove autosuggest on the name field. If people are searching for a name, they know the name. It's not like a department where they type police and don't know that there are several districts that the police department is divided into. by removing it for the name field then we avoid issues on larger data sets like the state salaries.

**Comment by ThomasThoren** [comment]
Good point about the bigger data sets. If ~4,500 rows are pushing the limit, then this won't work for most applications.

**Comment by ThomasThoren** [comment]
Removed autocomplete in 466df7aeb521409cdf74bfcf3c6213b056a71b9f.
