### ISSUE TITLE
Create unique URLs to improve SEO

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/citysalaries#5]
![screenshot 2015-06-08 16 17 07](https://cloud.githubusercontent.com/assets/413882/8045580/e65091b2-0df9-11e5-9d80-a92706b5449a.png)

I searched for this woman, a public employee in texas, and one of the top links is the TX Trib salary explorer. Let's discuss whether we can do this.

**Comment by ThomasThoren** [comment]
Giving each employee their own page like that would require a good amount of additional work, though it is possible. The Texas Tribune's pages include more data, along with information about where the employee fits in.

Right now, I'm only trying to add custom URLs for each search. That will allow people to share a given employee, though I don't know that it will boost the SEO at all.

**Comment by smyerslens** [comment]
Let's table this until we have some more info to share on the individual page.
