### ISSUE TITLE
Move the pager components to the top right corner of the search results and also place at the bottom

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/citysalaries#6]
Separate the pager components from the "X results found" area.

**Comment by smyerslens** [comment]
Unclear on what this means.

**Comment by ThomasThoren** [comment]
@myersnews The "X results found" output and pager options are all crammed in the top left, but they should have their own separate areas on the page.

**Comment by ThomasThoren** [comment]
Fixed with 2c08575b9015319290b9af078a5bf80be7ccd765.
