### ISSUE TITLE
Data doesn't load immediately, so quick first searches always fail

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/citysalaries#7]
If you search as soon as the page "loads", nothing happens because the data hasn't been fully loaded yet. It requires waiting a second or two. This isn't all that noticeable, but best to fix if we can.

**Comment by ThomasThoren** [comment]
If we put Google Consumer Surveys on this page, that could "fix" this problem since the data will load in the background.

**Comment by smyerslens** [comment]
You can put a spinning wheel there for this amount of time. It delays the user but tells them that the app isn't quite ready. However, if we keep GCS on this, which we have done, then that also fixes it as you said.

**Comment by ThomasThoren** [comment]
The data is gzipped now, so this shouldn't be a problem any longer.
