### ISSUE TITLE
Check for outliers and verify; check for absent departments and positions

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/citysalaries#9]

**Comment by ThomasThoren** [comment]
Sewerage and Water Board employees are absent. Find out why.

**Comment by smyerslens** [comment]
## That’s an independent agency; they shouldn’t be in there. They weren’t last time, right?

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
You're right. SWB wasn't included last year either. I didn't see Cedric Grant's name but forgot he moved into SWB in the last year.

**Comment by ThomasThoren** [comment]
Everything seems kosher.
